#!/bin/bash

scriptdir="$(dirname $(readlink -f -- $BASH_SOURCE))"
reservedleftscript="$scriptdir/reservedleft"

filename=".i3-gaps-off"

off="${XDG_RUNTIME_DIR:-/tmp}/$filename"
if [[ -f $off ]]; then
    offstate=true
else
    offstate=false
fi

if [[ $1 == "keep" ]]; then
    if [[ $offstate == true ]]; then
        offstate=false
    else
        offstate=true
    fi
fi

if [[ $offstate == "true" || $1 == "on" ]]; then
    i3-msg gaps outer current set 15
    i3-msg gaps inner current set 15
    rm -f "$off"
else
    i3-msg gaps outer current set 0
    i3-msg gaps inner current set 0
    touch "$off"
fi

i3-msg gaps left current plus $("$reservedleftscript" get)
