#!/bin/bash

filename=".i3-gaps-off"

off="${XDG_RUNTIME_DIR:-/tmp}/$filename"

if [[ -f $off || $1 == "on" ]]; then
    i3-msg gaps outer all set 15
    i3-msg gaps inner all set 15
    rm -f "$off"
else
    i3-msg gaps outer all set 0
    i3-msg gaps inner all set 0
    touch "$off"
fi
